
export { default as pro13Max } from '../assets/13-pro-max.jpg'
export { default as pro14Max } from '../assets/14-pro-max.jpg'
export { default as s24Ultra } from '../assets/s24-ultra.jpg'
export { default as s23Ultra } from '../assets/s23-ultra.jpg'
export { default as watch1 } from   '../assets/watch1.jpg'
export { default as watch2 } from   '../assets/watch2.jpg'
export { default as watch3 } from   '../assets/watch3.jpg'
export { default as watch4 } from   '../assets/watch4.jpg'
export { default as headset1 } from '../assets/headset1.jpg'
export { default as headset2 } from '../assets/headset2.jpg'
export { default as headset3 } from '../assets/headset3.jpg'
export { default as headset4 } from '../assets/headset4.jpg'
export { default as accessory1 } from '../assets/access1.jpg'
export { default as accessory2 } from '../assets/access2.jpg'
export { default as accessory3 } from '../assets/access3.jpg'